### ISSUE TITLE
Update to JSON API 1.0

### ISSUE THREAD

**Issue by alanpeabody** [AgilionApps/relax#4]

**Comment by hunterboerner** [comment]
Status?

**Comment by alanpeabody** [comment]
On the top of my "Want to do" list behind my "need to do" list.

I have not started it yet but I am actively looking at other JSON API implementations in other languages to determine how much this library should do and how much it should leave to other tools/frameworks.

I would love to hear your uses case and what you would like to see out of this library.

**Comment by joaomdmoura** [comment]
hey @alanpeabody just in case you want to check it, we at [AMS](https://github.com/rails-api/active_model_serializers) have implemented it some while ago :smile: btw let me know if you need some help with it

**Comment by alanpeabody** [comment]
@joaomdmoura thanks!

I am looking at AMS and also https://github.com/cerebris/jsonapi-resources as inspiration.

I have a couple of agendas during this update:

1. Refactor the internals to use Protocols for easier overriding of certain behavior. This will be better when serializing structs that are treated as low level data structures (eg Ecto.DateTime).
2. Extract the routing to it's own library.
3. Keep the initial implementation simple, not trying to cover the spec 100% until after some real world usage dictates what is actually useful in this library.
4. Make Phoenix support first class.
5. Improve testing.

I will try to take a first stab in the next 5 days and will ping both of you for feedback, but I likely won't be able to focus a significant amount of time until the week of July 6th.

**Comment by alanpeabody** [comment]
@joaomdmoura @hunterboerner I have moved serialization to a new library and updated it to match the spec for JSONAPI 1.0. https://github.com/AgilionApps/ja_serializer

Relax will be implementing a more full JSON API implementation inspired by  https://github.com/cerebris/jsonapi-resources but continuing to leverage the ja_serializers library. Contributions, bug reports, feedback and feature requests are appreciated for both libraries.

**Comment by joaomdmoura** [comment]
awesome @alanpeabody.
Glad to hear that! we have being following jsonapi-resources too. :smile:
