### ISSUE TITLE
Why does the generated as_json method require the meta parameter?

### ISSUE THREAD

**Issue by amutz** [AgilionApps/relax#8]
Hello,

I'm trying out Relax, and in the documentation provided, the as_json method can be invoked as such: 
```
PostSerializer.as_json(conn)
```

However, in my use it seems to be expecting a second argument ("meta"):

```
PostSerializer.as_json(conn, %{})
```

Why is this second argument mandatory?  Am I missing something or are the docs out of date?

Thanks,
Andrew.

**Comment by alanpeabody** [comment]
Hi Andrew,

It looks like the docs are wrong, sorry about that.

The generated `as_json/3` method actually has an arity of 3: `PostSerializer.as_json(model, conn, meta)`. Meta can be either a map or nil, typically used for pagination etc.

Are you using Relax with Phoenix? I have yet to actually do that, so the Relax Serialization APIs may not be an awesome fit yet. (I am using Relax.Responders in regular mix apps).

I am contemplating moving the serialization DSL to it's own lib that would be a better fit with Phoenix, but I have not had the time recently. I should also note that jsonapi.org 1.0 was just released but this library still is implementing jsonapi.org RC1. I hope to address both of these issues in the medium term future, but I would welcome feedback in the meantime!

**Comment by amutz** [comment]
Ok great, thanks.

Yes I am using it with Phoenix.  Right now I am smoothing over issues like this by making macros in my web.ex file that abstract away things like the extra meta parameter (that I havent needed yet).

When I get more experience with using Relax and Phoenix, I'll give you my feedback.

Thanks!
-Andrew.

**Comment by alanpeabody** [comment]
@amutz I have migrated the serialization aspect of this library to https://github.com/AgilionApps/ja_serializer . You may find this a it cleaner when working with Phoenix, but be advised it is now formatting in accordance with the JSONAPI 1.0 spec.

Relax will move towards being a more complete routing oriented library similar to https://github.com/cerebris/jsonapi-resources.

Please let me know if you run into any errors.
